---
- hosts: vm-ubuntu
  become: yes
  become_method: sudo


  roles:
    - { role: common, tags: common }
    - { role: clamav, tags: clamav }
    - { role: teamviewer, tags: teamviewer }
    - { role: security, tags: security }


  tasks:
    - name: Upgrade system
      apt: upgrade=full

    - name: reboot system
      shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
