---
common_pkg_prerequisites:
  - python-software-properties
  - software-properties-common
  - aptitude

common_ppa_repositories14:
  - ppa:libreoffice/ppa
  - ppa:savoirfairelinux

common_ppa_repositories16:
  - ppa:libreoffice/ppa

common_system_pkgs:
  - chromium-browser
  - firefox
  - gscan2pdf

system_pkgs_14:
  - unetbootin
  - openjdk-7-jdk
  - openjdk-7-jre
  - ubuntu-restricted-extras
  - ubuntu-restricted-addons
  - sflphone-gnome
  - sflphone-plugins

system_pkgs_16:
  - unetbootin
  - openjdk-8-jdk
  - openjdk-8-jre
  - ubuntu-restricted-extras
  - ubuntu-restricted-addons
  - twinkle

