---
#- name: Download Teamviwer version 10
#  get_url: url="{{ tviewer_url }}" dest="{{ tviewer_downloads_prefix }}/teamviewer_i386.deb"

- name: Copy Tviewer installationfile
  copy: src=teamviewer_i386.deb dest="{{ tviewer_downloads_prefix }}" mode=0775 force=yes

- name: Install Teamviwer
  apt: deb="{{ tviewer_downloads_prefix }}/teamviewer_i386.deb"

- name: Copy Tviewer script to destination system
  copy: src=tviewer_start.sh dest="{{ tviewer_downloads_prefix }}" mode=0774 force=yes

- name: Configure TViewer on the remote machine
  command: "{{ tviewer_downloads_prefix }}/tviewer_start.sh"

- name: Removing configuration file
  file: path="{{ tviewer_downloads_prefix }}/tviewer_start.sh" state=absent

- name: Set default password
  command: teamviewer passwd "{{ tviewer_pwd }}"






