---
- name: Test distribution
  fail: msg="Not Ubuntu, aborting"
  when: ansible_distribution != "Ubuntu"

- name: Install prerequisites for PPA management
  apt: name={{ item }} state=latest force=yes
  with_items:
    - "{{ common_pkg_prerequisites }}"

- name: Add PPAs for common packages
  apt_repository: repo={{ item }} update_cache=yes
  with_items:
    - "{{ common_ppa_repositories }}"

- name: Update system repositories
  apt: update_cache=yes

- name: Install common packages
  package: name={{ item }} state=latest
  with_items:
    - "{{ common_system_pkgs }}"
    - "{{ common_browser_pkgs }}"

- name: Install softphone
  package: name={{ item }} state=latest
  with_items:
    - "{{ common_softphone_pkgs }}"





