---
- name: Test distribution
  fail: msg="Not Ubuntu or invalid OS version, aborting..."
  when:
    - ansible_distribution != "Ubuntu"
    - ansible_distribution_version != '14.04' or ansible_distribution_version != '16.04'

- name: Install prerequisites for PPA management
  apt: name={{ item }} state=latest force=yes
  with_items:
    - "{{ common_pkg_prerequisites }}"

- name: Add PPAs repositories for Ubuntu 14.04
  apt_repository: repo={{ item }} update_cache=yes
  with_items:
    - "{{ common_ppa_repositories14 }}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Add PPAs repositories for Ubuntu 16.04
  apt_repository: repo={{ item }} update_cache=yes
  with_items:
    - "{{ common_ppa_repositories16 }}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Add canonical repositories
  apt_repository: repo='deb http://archive.canonical.com/ubuntu {{ansible_distribution_release}} partner' state=present

- name: Update system repositories
  apt: update_cache=yes

- name: Install common packages
  package: name={{ item }} state=latest
  with_items:
    - "{{ common_system_pkgs }}"
    - "{{ common_browser_pkgs }}"

- name: Installing softphone software SFLPhone if running ubuntu 14.04
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: yes
    force: yes
  with_items:
    - "{{ common_softphone_pkgs14 }}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Installing softphone software TWINKLE if running ubuntu 16.04
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: yes
    force: yes
  with_items:
    - "{{ common_softphone_pkgs16 }}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Download Chrome browser package
  get_url:
    url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    dest: "/tmp/google_chrome.deb"
    force: yes

- name: Install chrome browser
  apt:
    deb: "/tmp/google_chrome.deb"
    force: yes



