---
- name: Test distribution
  fail: msg="Not Ubuntu, aborting"
  when: ansible_distribution != "Ubuntu"

- name: Install prerequisites for PPA management
  apt: name={{ item }} state=latest force=yes
  with_items:
    - "{{ common_pkg_prerequisites }}"

- name: Add PPAs repositories for Ubuntu 14.04
  apt_repository: repo={{ item }} update_cache=yes
  with_items:
    - "{{ common_ppa_repositories14 }}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

  apt_repository: repo={{ item }} update_cache=yes
  with_items:
    - "{{ common_ppa_repositories16 }}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Add sflphone trusty repos manually for version 16.04
  blockinfile:
    path: /etc/apt/sources.list
    block: |
      ## trusty repositories for SFLPhone
      deb http://ppa.launchpad.net/savoirfairelinux/ppa/ubuntu trusty main
      deb-src http://ppa.launchpad.net/savoirfairelinux/ppa/ubuntu trusty main
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Update system repositories
  apt: update_cache=yes

- name: Install common packages
  package: name={{ item }} state=latest
  with_items:
    - "{{ common_system_pkgs }}"
    - "{{ common_browser_pkgs }}"

- name: Install softphone
  package: name={{ item }} state=latest
  with_items:
    - "{{ common_softphone_pkgs }}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'





